### ISSUE TITLE
Compatibility with Python3 and Octoprint 1.4.0

### ISSUE THREAD

**Issue by asmfreak** [jim-p/Change_Filament#18]
I've tried installing this plugin on Octoprint 1.4.0rc3.
The plugin installed without any errors, but the frontend didn't change a bit.

**Comment by jim-p** [comment]
Probably because I need to add the bits to mark it as compatible. I meant to test this locally in a test setup but now that 1.4.0 is out I'll test it on one of my live printers. Should be fairly easy once I manage to get my installs updated to 1.4.0.

https://github.com/foosel/OctoPrint/releases/tag/1.4.0
https://octoprint.org/blog/2020/03/04/new-release-candidate-1.4.0/
https://docs.octoprint.org/en/master/plugins/python3_migration.html

**Comment by jim-p** [comment]
Upstream change also needed: https://github.com/OctoPrint/plugins.octoprint.org/pull/408

Once that is merged it should start showing up.

**Comment by jim-p** [comment]
Upstream change merged, plugin shows up for installation on OctoPrint 1.4.0 with Python 3.x, installs and shows up as expected.

**Comment by asmfreak** [comment]
Thanks! It works great!
